language: r
sudo: required
git:
  depth: 3
r:
  - release
cache: packages
r_packages:
   - shiny
   - magrittr
   - ggplot2
   - openssl
   - XML
   - plotly
   - shinydashboard
   - emdbook
   - testthat
   - covr
addons:
  apt:
    packages:
      - r-cran-xml
      - libcurl4-gnutls-dev
      - libxml2-dev
      - openssl
      - gdebi-core
before_script:
  - cd tests/
script:
  - Rscript -e "x <- testthat::test_dir("dashboard/tests/") %>% data.frame() %>% .[["error"]] %>% any(); if (x == T) write("1", stderr())" 
after_success:
  - cd ..
  - Rscript -e 'covr::codecov()'
