language: r
sudo: required
r:
  - release
cache: packages
r_packages:
  - shiny
  - magrittr
  - ggplot2
  - openssl
  - XML
  - plotly
  - shinydashboard
  - emdbook
  - testthat
addons:
  apt:
    packages:
      - r-cran-xml
      - libcurl4-gnutls-dev
      - libxml2-dev
      - openssl
      - gdebi-core
script:
  - Rscript -e "testthat::test_dir('tests')"
