language: r
sudo: required
git:
  depth: 3
r:
  - release
cache: packages
r_packages:
   - shiny
   - lintr
   - magrittr
   - ggplot2
   - openssl
   - XML
   - plotly
   - shinydashboard
   - emdbook
   - testthat
   - purrr
   - covr
addons:
  apt:
    packages:
      - r-cran-xml
      - libcurl4-gnutls-dev
      - libxml2-dev
      - openssl
      - gdebi-core
before_script:
  - cd tests/
script:
  - Rscript -e "library(magrittr); error <- testthat::test_file('test_funcs.R') %>% data.frame() %>% dplyr::select(failed); if (sum(error$failed) > 0){ error %>% dplyr::filter(failed > 0) %>% print(); q(save = 'no', status = 1) }"
after_success:
- Rscript -e "x <- covr::file_coverage(source_files = c('../functions/bayesian_functions.R'), test_files = c('test_funcs.R')); covr::codecov(coverage = x)"
- Rscript -e "library(magrittr); error <- testthat::test_file('test_lint.R') %>% data.frame() %>% dplyr::select(failed); if (sum(error$failed) > 0){ error %>% dplyr::filter(failed > 0) %>% print(); q(save = 'no', status = 1) }"
