language: r
sudo: required
git:
  depth: 3
r:
  - release
cache: packages
r_packages:
   - shiny
   - magrittr
   - ggplot2
   - openssl
   - XML
   - plotly
   - shinydashboard
   - emdbook
   - testthat
   - covr
addons:
  apt:
    packages:
      - r-cran-xml
      - libcurl4-gnutls-dev
      - libxml2-dev
      - openssl
      - gdebi-core
before_script:
  - cd tests/
script:
  - make test
  - echo $TRAVIS_TEST_RESULT
after_success:
  - cd ..
  - Rscript -e 'covr::codecov()'
